name: inversion_ideas-debug
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  # Requirements
  - numpy>=2.0.0
  - scipy
  - rich
  # - simpeg==0.25.2
  - pymatsolver==0.4.0
  - discretize==0.12.0
  - pydiso
  # Required by notebooks
  - harmonica
  - verde
  - bordado
  - pandas
  # Jupyter
  - jupyter
  # Dev
  - pytest
  - pytest-cov
  - coverage
  - ruff
  - mypy
  - scipy-stubs
  # Docs
  - sphinx
  - numpydoc
  - pydata-sphinx-theme
  - sphinx-design
  - pip:
    # Commit from nsem_fictitious_sources branch
    # (I comment this one bc I'm installing SimPEG from a local folder in editor mode, just for debugging)
    # - git+https://github.com/simpeg/simpeg.git@3b722ceb97768c54a84eb0d8d39440d5cf176e48
