# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'inversion-ideas'
copyright = '2026, SimPEG Developers'
author = 'SimPEG Developers'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Autosummary pages will be generated by sphinx-autogen instead of sphinx-build
autosummary_generate = True

numpydoc_class_members_toctree = False  # Avoid cluttering TOC with inherited members
numpydoc_attributes_as_param_list = False
numpydoc_show_inherited_class_members = True  # Show inherited methods in docs

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'pydata_sphinx_theme'
html_static_path = ['_static']

html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/simpeg/inversion-design-ideas",
            "icon": "fab fa-github",
        },
    ],
    "use_edit_page_button": False,
    "collapse_navigation": False,
    "navigation_with_keys": True,
}

html_context = {
    "github_user": "simpeg",
    "github_repo": "inversion-design-ideas",
    "github_version": "main",
    "doc_path": "docs",
}
html_static_path = []  # avoid warning by overwriting the default ["_static"]

